import {useState} from 'react';
import PrototypeChart from './PrototypeChart.jsx';
import {DEMO_CANDLES,SAMPLE_METHODS,createMethod,constrainPlan,preview,makeRequest,validateRequest,confirmRequest,manage,amendExits} from './prototypeModel.js';
import usePanelResize from '../workspace/usePanelResize.js';
import WorkspaceModal from '../workspace/WorkspaceModal.jsx';
import '../FigmaWorkspace.css';
import '../FxWorkspace.css';
import '../workspace/designTokens.css';
import './prototype.css';
const initialPlan=()=>({workflow:'PLANNED',side:'Buy',type:'Limit',entry:2330,sl:2328,tp:2334,riskMode:'PERCENT',risk:1,size:1,time:DEMO_CANDLES[65].time,checklist:{}});
const format=n=>Number.isFinite(n)?n.toFixed(3):'Unavailable';
const lots=n=>Number.isFinite(n)?n.toFixed(4):'Unavailable';
export default function TradingUxPrototype(){
  const [methods,setMethods]=useState(SAMPLE_METHODS),[methodId,setMethodId]=useState('free');
  const method=methods.find(m=>m.id===methodId);
  const [plan,setPlan]=useState(initialPlan),[revision,setRevision]=useState(1),[quote,setQuote]=useState({price:2332,revision:1});
  const [placing,setPlacing]=useState(false),[locked,setLocked]=useState(false),[hidden,setHidden]=useState(false),[chooser,setChooser]=useState(false),[favorites,setFavorites]=useState([]);
  const [dialog,setDialog]=useState(null),[review,setReview]=useState(null),[registry,setRegistry]=useState({}),[items,setItems]=useState([]),[events,setEvents]=useState([]),[notice,setNotice]=useState('Choose a sample Method; all state is memory-only.'),[methodError,setMethodError]=useState('');
  const resize=usePanelResize(150,120),stats=preview(method,plan),effective=stats.plan;
  const request=makeRequest(method,effective,quote,revision,'request:'+revision),reasons=validateRequest(method,request,quote,revision);
  const record=(kind,payload,context=request)=>setEvents(current=>[...current,{id:current.length+1,kind,methodId:context.methodId,sessionId:context.sessionId,revision:context.revision,quoteRevision:context.quoteRevision,enforcement:context.enforcement,checklist:context.checklist,source:'PROTOTYPE',payload}]);
  const edit=(patch,index)=>{
    if(locked){setNotice('Plan is locked. Unlock to edit.');return;}
    if(method.type==='PROTOCOL'&&index===2){setNotice('PROTOCOL: TP is derived from locked RR. Move Entry or SL.');return;}
    setPlan(current=>constrainPlan(method,{...current,...patch}));setRevision(r=>r+1);setReview(null);
  };
  const selectMethod=id=>{setMethodId(id);setPlan(initialPlan());setRevision(r=>r+1);setDialog(null);setReview(null);setLocked(false);setPlacing(false);setNotice('Sample Session inherits Method; DEMO feed and starting basis remain fixed.');};
  const chooseTool=side=>{if(locked){setNotice('Unlock plan before selecting another direction.');return;}edit({side,workflow:'PLANNED',type:'Limit',sl:effective.entry+(side==='Buy'?-2:2),tp:effective.entry+(side==='Buy'?4:-4)});setPlacing(true);setChooser(false);setNotice('Click the synthetic chart to place Entry; then move SL/TP handles or edit fields.');};
  const openQuick=side=>{if(method.type==='PROTOCOL'){setNotice('PROTOCOL: Quick prohibited; use Planned pending Limit/Stop.');record('REFUSED',{action:'QUICK',reason:'Protocol Planned-only'});return;}if(locked){setNotice('Unlock the plan before switching journey.');return;}edit({workflow:'QUICK',side,type:'Market',entry:quote.price,sl:null,tp:null,size:1});setDialog('ticket');};
  const act=(item,action)=>{const owner=methods.find(m=>m.id===item.request.methodId),out=manage(owner,item,action);if(out.reason){setNotice(out.reason);record('REFUSED',{requestId:item.request.id,action,reason:out.reason},item.request);return;}if(out.amend){setMethodError('');setDialog({amend:item});return;}setItems(current=>current.map(i=>i.request.id===item.request.id?out.item:i));record('SCENARIO_'+action.toUpperCase(),{requestId:item.request.id,state:out.item.state,remaining:out.item.remaining},item.request);setNotice('Synthetic lifecycle representation only; no fill/P&L or account mutation.');};
  const confirm=()=>{const out=confirmRequest(registry,method,review,quote,revision);if(out.reasons.length){setNotice(out.reasons.join(' '));record('REFUSED',{reasons:out.reasons});setDialog(null);return;}setRegistry(out.registry);if(!out.duplicate)setItems(current=>[...current,out.result]);record(out.duplicate?'DUPLICATE_ACK':'CONFIRMED',review);setDialog(null);setNotice('Confirmed simulation only — '+out.result.state+'. v1 account unchanged.');};
  return <main className="ux-prototype">
    <header><div><strong>Backtest Lab</strong><span className="ux-badge">Trading UX prototype · memory-only</span></div><a href="/">Return to local v1</a></header>
    <section className="ux-session" aria-label="Sample research context"><label>Trading Method<select aria-label="Trading Method" value={methodId} onChange={e=>selectMethod(e.target.value)}>{methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><button onClick={()=>{setMethodError('');setDialog('method');}}>Create demo Method</button><span>Session demo-session:{method.id} · DEMO:XAUUSD · DEMO_SYNTHETIC</span><span>Basis $100,000 · tick .001 · 100 units/lot · zero-cost demo</span></section>
    <div className="ux-workspace"><section className="ux-chart-area"><nav aria-label="Prototype planning tools"><button aria-expanded={chooser} onClick={()=>setChooser(v=>!v)}>Position tools ▾</button><button aria-pressed={locked} onClick={()=>setLocked(v=>!v)}>{locked?'Unlock plan':'Lock plan'}</button><button aria-pressed={hidden} onClick={()=>setHidden(v=>!v)}>{hidden?'Show plan':'Hide plan'}</button><span>Available prototype tools: Cursor, Long, Short</span></nav>
      {chooser&&<div className="ux-chooser" onKeyDown={e=>{if(e.key==='Escape'){setChooser(false);e.currentTarget.ownerDocument.querySelector('[aria-label="Prototype planning tools"] button')?.focus();}}}><strong>POSITION PLANNING</strong>{['Buy','Sell'].map(side=><div key={side}><button aria-pressed={effective.side===side&&effective.workflow==='PLANNED'} onClick={()=>chooseTool(side)}><span aria-hidden="true">{side==='Buy'?'↗':'↘'}</span> {side==='Buy'?'Long':'Short'} Position</button><button aria-label={'Favorite '+side} aria-pressed={favorites.includes(side)} onClick={()=>setFavorites(current=>current.includes(side)?current.filter(s=>s!==side):[...current,side])}>{favorites.includes(side)?'★':'☆'}</button><button aria-label={'Help '+side} onClick={()=>setNotice('Entry + stop + target preview. Placement never submits. Protocol derives TP and size.')}>ⓘ</button></div>)}<button onClick={()=>{setPlacing(false);setChooser(false);}}>Cursor / Select</button></div>}
      <PrototypeChart plan={effective} placing={placing} locked={locked} hidden={hidden} onPlace={(entry,time)=>{edit({entry,time,type:(entry-quote.price)*(effective.side==='Buy'?1:-1)<0?'Limit':'Stop',sl:entry+(effective.side==='Buy'?-2:2),tp:entry+(effective.side==='Buy'?4:-4)});setPlacing(false);}} onEdit={edit}/>
      <div className="ux-bottom"><button onClick={()=>openQuick('Buy')}>Quick Buy</button><button onClick={()=>openQuick('Sell')}>Quick Sell</button><button onClick={()=>{setQuote(q=>({price:q.price+.001,revision:q.revision+1}));if(effective.type==='Market'){setPlan(p=>({...p,entry:quote.price+.001}));setRevision(r=>r+1);}setReview(null);setNotice('Demo quote advanced; revalidate any review.');}}>Advance demo quote</button><span>Quote {format(quote.price)} · revision {quote.revision}</span><button onClick={resize.restore}>Show terminal</button></div>
    </section><aside className="ux-planner" aria-label="Trading plan">
      <h1>{method.type==='PROTOCOL'?'Protocol':'Free Style'} · {effective.workflow==='QUICK'?'Quick':'Planned'}</h1><p>{method.type==='PROTOCOL'?`Locked risk ${method.risk}% · RR ${method.rr} · checklist ${method.enforcement?'ON':'OFF'}`:'Discretionary geometry and risk. No Protocol checklist.'}</p>
      <label>Pending / order type<select aria-label="Order type" disabled={locked} value={effective.type} onChange={e=>edit({type:e.target.value,...(e.target.value==='Market'?{entry:quote.price}:{})})}>{['Market','Limit','Stop'].map(type=><option key={type} disabled={method.type==='PROTOCOL'&&type==='Market'}>{type}</option>)}</select></label>
      {['entry','sl','tp'].map(key=><label key={key}>{key==='entry'?'Entry':key.toUpperCase()}<input aria-label={key==='entry'?'Entry':key.toUpperCase()} type="number" step=".001" disabled={locked||(key==='tp'&&method.type==='PROTOCOL')||(key==='entry'&&effective.type==='Market')} value={effective[key]??''} onChange={e=>edit({[key]:e.target.value===''?null:Number(e.target.value)},key==='tp'?2:undefined)}/></label>)}
      {effective.workflow==='QUICK'?<label>Lots<input aria-label="Lots" type="number" step=".0001" value={effective.size} onChange={e=>edit({size:Number(e.target.value)})}/></label>:<><label>Risk unit<select aria-label="Risk unit" disabled={locked||method.type==='PROTOCOL'} value={effective.riskMode} onChange={e=>edit({riskMode:e.target.value})}><option value="PERCENT">Percent of demo basis</option><option value="CASH">USD amount</option></select></label><label>Risk value<input aria-label="Risk value" type="number" disabled={locked||method.type==='PROTOCOL'} value={effective.risk} onChange={e=>edit({risk:Number(e.target.value)})}/></label><dl><dt>Risk budget USD</dt><dd>{format(stats.budget)}</dd><dt>Derived lots</dt><dd>{lots(stats.size)}</dd><dt>RR preview</dt><dd>{format(stats.rr)}</dd><dt>Planned loss USD</dt><dd>{format(stats.loss)}</dd></dl></>}
      {method.type==='PROTOCOL'&&<fieldset><legend>Checklist · {method.enforcement?'all PASS required':'optional, evidence retained'}</legend>{method.conditions.map(condition=><label key={condition}>{condition}<select aria-label={condition} value={effective.checklist[condition]??'NOT_ASSESSED'} onChange={e=>edit({checklist:{...effective.checklist,[condition]:e.target.value}})}>{['NOT_ASSESSED','FAIL','PASS'].map(s=><option key={s}>{s}</option>)}</select></label>)}</fieldset>}
      <div role="status" className={reasons.length?'ux-warning':'ux-ready'}>{reasons.length?reasons.join(' '):'READY · request valid under disclosed demo assumptions'}</div><button onClick={()=>setDialog('ticket')}>Open Order Ticket</button><p>Plan placement/editing never executes. Prototype does not persist Methods, Sessions, orders or evidence.</p>
    </aside></div>
    <section className="ux-terminal" style={{height:resize.height}} data-terminal-state={resize.state}><div role="separator" aria-label="Resize prototype terminal" aria-orientation="horizontal" aria-valuemin={resize.min} aria-valuemax={resize.max} aria-valuenow={resize.height} aria-valuetext={resize.state} tabIndex={0} className="positions-resize" onPointerDown={resize.start} onKeyDown={resize.keyDown}><span aria-hidden="true"/></div><div hidden={resize.state==='COLLAPSED'} className="ux-terminal-content"><h2>Simulated orders / positions · no canonical P&amp;L</h2>{!items.length?<p>No confirmed simulation</p>:items.map(item=><div className="ux-item" key={item.request.id}><strong>{item.request.side} {item.request.type} · {item.state} · remaining {(item.remaining*100).toFixed(0)}%</strong><span>{item.request.methodId} · {item.request.id}</span>{item.state==='pending'?<><button onClick={()=>act(item,'trigger')}>Simulate trigger</button><button onClick={()=>act(item,'cancel')}>Cancel pending</button></>:['active_position','partially_exited'].includes(item.state)&&<><button onClick={()=>act(item,'amend')}>Edit exits</button><button onClick={()=>act(item,'partial')}>Close 50%</button><button onClick={()=>act(item,'close')}>Manual close</button><button onClick={()=>act(item,'plannedExit')}>Simulate planned exit</button></>}</div>)}<details><summary>Prototype evidence ({events.length})</summary><pre>{JSON.stringify(events,null,2)}</pre></details></div></section>
    <footer role="status">{notice}</footer>
    {dialog==='ticket'&&<WorkspaceModal label="Prototype Order Ticket" onClose={()=>setDialog(null)}><section className="ux-dialog"><h2>Order Ticket · simulation only</h2><p>{method.name} · {effective.side} {effective.type} · {effective.workflow}</p><p>Entry {format(request.entry)} · SL {format(request.sl)} · TP {format(request.tp)} · lots {lots(request.size)}</p><p>Edit levels/risk in the planner before review. Identity and locked Method values are inherited.</p>{reasons.length>0&&<p role="alert">{reasons.join(' ')}</p>}<button onClick={()=>setDialog(null)}>Cancel / return to edit</button><button disabled={Boolean(reasons.length)} onClick={()=>{setReview(request);setDialog('review');}}>Review request</button></section></WorkspaceModal>}
    {dialog==='review'&&review&&<WorkspaceModal label="Explicit order confirmation" onClose={()=>{setDialog(null);setReview(null);}}><section className="ux-dialog"><h2>Confirm simulated {review.type==='Market'?'immediate position':'pending order'}</h2><p>{review.side} · {review.type} · Entry {format(review.entry)} · SL {format(review.sl)} · TP {format(review.tp)} · lots {lots(review.size)}</p><p>{method.name} · {review.sessionId} · revision {review.revision}. Zero-cost synthetic preview; no real execution.</p><pre>{JSON.stringify(review.checklist,null,2)}</pre><button onClick={()=>{setDialog(null);setReview(null);}}>Cancel confirmation</button><button onClick={confirm}>Confirm simulation</button></section></WorkspaceModal>}
    {dialog==='method'&&<WorkspaceModal label="Create demo Trading Method" onClose={()=>setDialog(null)}><form className="ux-dialog" onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget);try{const created=createMethod({name:fields.get('name'),rr:Number(fields.get('rr')),risk:Number(fields.get('risk')),conditions:String(fields.get('conditions')).split('\n').filter(c=>c.trim()),enforcement:fields.get('enforcement')==='ON'});if(methods.some(m=>m.id===created.id))throw new Error('Use a unique demo Method name.');setMethods(current=>[...current,created]);setMethodId(created.id);setPlan(initialPlan());setRevision(r=>r+1);setLocked(false);setDialog(null);}catch(error){setMethodError(error.message);}}}><h2>Create immutable demo Protocol Method</h2><label>Name<input name="name" required/></label><label>Locked RR<input name="rr" type="number" step="any" defaultValue="2" required/></label><label>Locked risk %<input name="risk" type="number" step="any" defaultValue="1" required/></label><label>Conditions (one per line)<textarea name="conditions" required/></label><label>Enforcement<select name="enforcement"><option>ON</option><option>OFF</option></select></label>{methodError&&<p role="alert">{methodError}</p>}<button type="button" onClick={()=>setDialog(null)}>Cancel</button><button>Create sample Method / Session</button></form></WorkspaceModal>}
    {dialog?.amend&&<WorkspaceModal label="Edit simulated exits" onClose={()=>setDialog(null)}><form className="ux-dialog" onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget),item=dialog.amend,sl=Number(fields.get('sl')),tp=Number(fields.get('tp')),out=amendExits(methods.find(m=>m.id===item.request.methodId),item,sl,tp);if(out.reason){setMethodError(out.reason);return;}setItems(current=>current.map(i=>i.request.id===item.request.id?out.item:i));record('SCENARIO_AMEND',{requestId:item.request.id,sl,tp},item.request);setDialog(null);}}><h2>Edit Free Style simulated exits</h2>{methodError&&<p role="alert">{methodError}</p>}<label>SL<input name="sl" type="number" step=".001" defaultValue={dialog.amend.currentExits?.sl??dialog.amend.request.sl??dialog.amend.request.entry+(dialog.amend.request.side==='Buy'?-2:2)}/></label><label>TP<input name="tp" type="number" step=".001" defaultValue={dialog.amend.currentExits?.tp??dialog.amend.request.tp??dialog.amend.request.entry+(dialog.amend.request.side==='Buy'?4:-4)}/></label><button type="button" onClick={()=>setDialog(null)}>Cancel amendment</button><button>Apply simulated exits</button></form></WorkspaceModal>}
  </main>;
}
