import {useState} from 'react';
import {ratioLabel} from './annotations.js';

const stamp=value=>value===null?'—':new Date(Number(BigInt(value)/1000000n)).toISOString();
const shown=value=>value??'Unavailable';

export default function AlphaTerminal({view,busy,onAction}){
  const [tab,setTab]=useState('Open positions'),[quantities,setQuantities]=useState({});
  const evidence=view.analysis;
  if(!evidence||evidence.status!=='COMPLETE')return <section className="alpha-terminal" aria-label="Trading and Analysis"><h2>Analysis unavailable</h2><p>{evidence?.reason??'The local service has no compatible analysis projection.'} No partial history is presented as a complete result. Reload the saved Session after resolving the limit.</p></section>;
  const {account,metrics,provenance}=evidence;
  const closed=tab==='Closed trades';
  const rows=tab==='Pending orders'?evidence.orders.filter(o=>o.status==='PENDING'):closed?evidence.completed:evidence.orders.filter(o=>['ACTIVE','UNRESOLVED'].includes(o.status));
  return <section className="alpha-terminal" aria-label="Trading and Analysis" data-event-head={provenance.eventHead} data-revision={provenance.revision}>
    <div className="alpha-account" aria-label="Committed account"><span>Balance <strong>${account.balance}</strong></span><span>Net cash change <strong>${account.netCashChange}</strong></span><span>Commission <strong>${account.commission}</strong></span><span>Indicative unrealized <strong>{account.unrealizedIndicative===null?'Unavailable':'$'+account.unrealizedIndicative}</strong></span><span>Indicative equity <strong>{account.equityIndicative===null?'Unavailable':'$'+account.equityIndicative}</strong></span></div>
    <p className="alpha-chart-note">Marks use the last revealed liquidation side: Bid for Long, Ask for Short. Marks are estimates; committed cash and completed-position metrics remain separate.</p>
    <div className="alpha-terminal-tabs" role="group" aria-label="Trading views">{['Open positions','Pending orders','Closed trades','Analysis','Evidence'].map(name=><button key={name} aria-pressed={tab===name} onClick={()=>setTab(name)}>{name}</button>)}</div>
    {tab==='Analysis'?<div className="alpha-analysis"><h2>Committed position Analysis</h2><dl>{[
      ['Completed trades',metrics.tradeCount],['Wins / losses / breakeven',`${metrics.wins} / ${metrics.losses} / ${metrics.breakeven}`],
      ['Win rate',ratioLabel(metrics.winRate,{percent:true})],['Average win (USD)',ratioLabel(metrics.averageWin)],['Average loss (USD)',ratioLabel(metrics.averageLoss)],
      ['Expectancy (USD)',ratioLabel(metrics.expectancy)],['Profit factor',ratioLabel(metrics.profitFactor)],['Longest win / loss streak',`${metrics.maxWinStreak} / ${metrics.maxLossStreak}`],
      ['Cash drawdown (USD)',metrics.maxDrawdown],['Cash drawdown %',ratioLabel(metrics.maxDrawdownRate,{percent:true})],['Unresolved / expired',`${metrics.unresolved} / ${metrics.expired}`],
    ].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><p>Only completed positions enter performance denominators. Partial exits stay within their original position. Ratios are rounded for display; money comes from committed exact postings.</p><p>R-multiple unavailable: initial R0 was not explicitly pinned before entry. {metrics.rExcluded} completed positions are excluded from R. Monte Carlo: insufficient eligible sample ({metrics.monteCarlo.eligible}/{metrics.monteCarlo.minimum}); no forecast. MAE/MFE and advanced research are not computed in this functional alpha.</p>
      <details><summary>Committed cash path ({evidence.equity.length} latest postings)</summary><p>Window starts at posting {metrics.equityWindowStart}. Drawdown scans the entire accepted bounded event history, not just this display window.</p><div className="alpha-table-scroll"><table><thead><tr><th>Event</th><th>UTC</th><th>Balance USD</th></tr></thead><tbody>{evidence.equity.map(row=><tr key={row.eventId}><td title={row.eventId}>{row.eventId.slice(0,12)}</td><td>{stamp(row.timeNs)}</td><td>{row.balance}</td></tr>)}</tbody></table></div></details></div>:tab==='Evidence'?<div className="alpha-analysis"><h2>Dataset and execution provenance</h2><dl>{Object.entries(provenance).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl><p>Authored synthetic fixture. QUOTE_BASELINE is a simulation, without broker liquidity, margin, variable fees, slippage or latency acceptance.</p><h3>Latest committed events</h3><p>Event window starts at {view.eventWindowStart}; account/Analysis verification uses the whole accepted bounded chain.</p><ol>{view.events.map(event=><li key={event.eventId}>{event.sequence}: {event.kind} · {event.classification} · <code>{event.eventId}</code></li>)}</ol></div>:<>
      <h2>{tab}</h2><div className="alpha-table-scroll"><table aria-label={tab}><thead><tr><th>Order</th><th>Direction</th><th>Status</th><th>Lots{closed?'':' remaining'}</th><th>Entry{tab==='Pending orders'?' intent':' fill'}</th><th>SL / TP</th>{closed?<><th>Last exit fill</th><th>Gross USD</th><th>Commission USD</th><th>Net USD</th><th>Duration</th></>:<><th>Indicative mark USD</th><th>Net cash change USD</th><th>Action</th></>}</tr></thead><tbody>{rows.map(order=><tr key={order.id} data-order-id={order.id}><td title={order.id}>{order.id.slice(-8)}</td><td>{order.side}</td><td>{order.status}{order.exitRequested?' · exit requested':''}</td><td>{closed?order.quantity:order.remaining}</td><td>{tab==='Pending orders'?order.entry:shown(order.entryPrice)}</td><td>{order.sl??'None'} / {order.tp??'None'}</td>{closed?<><td>{order.exitPrice} · {order.exitReason}</td><td>{order.gross}</td><td>{order.commission}</td><td>{order.net}</td><td>{String(BigInt(order.durationNs)/1000000000n)} s</td></>:<><td>{shown(order.unrealizedIndicative)}</td><td>{order.netCashChange}</td><td>{order.status==='PENDING'?<button disabled={busy||view.state.unresolved||view.state.ended} onClick={()=>onAction(order,'CANCEL')}>Cancel pending</button>:order.status==='ACTIVE'?<><button disabled={busy||order.exitRequested||view.method.kind==='PROTOCOL'||view.state.ended} onClick={()=>onAction(order,'CLOSE')}>Close position</button><label>Partial lots<input aria-label={`Partial lots ${order.id}`} inputMode="decimal" value={quantities[order.id]??''} disabled={busy||order.exitRequested||view.method.kind==='PROTOCOL'} onChange={event=>setQuantities(value=>({...value,[order.id]:event.target.value}))}/></label><button disabled={busy||order.exitRequested||view.method.kind==='PROTOCOL'||!quantities[order.id]} onClick={()=>onAction(order,'CLOSE',quantities[order.id])}>Partial close</button></>:<span>Unresolved; no invented settlement</span>}</td></>}</tr>)}{!rows.length&&<tr><td colSpan={closed?11:9}>No {tab.toLowerCase()}.</td></tr>}</tbody></table></div>
      {view.method.kind==='PROTOCOL'&&<p>Protocol positions keep locked exits. Manual and partial close are unavailable; pending cancellation is allowed.</p>}
      {closed&&<details><summary>Trace completed positions to committed fill evidence</summary>{rows.map(order=><article key={order.id}><h3>{order.id}</h3><p>Entry {stamp(order.entryTimeNs)} · ${order.entryPrice} · <code>{order.entryFillRef}</code></p><p>Final exit {stamp(order.exitTimeNs)} · ${order.exitPrice} · <code>{order.exitFillRef}</code></p><p>Net is the sum of this position’s committed cash postings, including all partial exits and entry/exit commission. The last exit price is not an average exit price.</p></article>)}</details>}
    </>}
  </section>;
}
