import './tickAlpha.css';
import {pagePath} from './client.js';

export default function AlphaHome(){
  const workspace=pagePath(),home=pagePath('home');
  return <main className="alpha-home">
    <header className="alpha-home-nav"><a className="alpha-wordmark" href={home}>Backtest Lab<span>RESEARCH WORKSPACE</span></a><nav aria-label="Main navigation"><a href="#method">Method</a><a href="#principles">Principles</a><a href={workspace}>Open workspace ↗</a></nav></header>
    <section className="alpha-home-hero"><div><p className="alpha-eyebrow">LOCAL ALPHA / MARKET RESEARCH</p><h1>Observe carefully.<br/>Test systematically.</h1><p className="alpha-home-intro">A focused environment for studying market behaviour, testing a defined method, and examining the evidence behind each result.</p><a className="alpha-home-primary" href={workspace}>Open research workspace <span aria-hidden="true">↗</span></a><p className="alpha-home-caption">Private local workspace · historical research · no live brokerage</p></div><div className="alpha-research-card" aria-label="Research process, illustrative diagram"><div className="alpha-research-caption"><span>RESEARCH PROCESS</span><span>01—04</span></div><ol>{[['Define','A question, a method, and rules fixed before the test.'],['Observe','Reveal historical evidence one step at a time.'],['Measure','Keep outcomes linked to their original evidence.'],['Review','Inspect uncertainty, limitations, and reproducibility.']].map(([title,text],index)=><li key={title}><span>0{index+1}</span><div><strong>{title}</strong><p>{text}</p></div></li>)}</ol><div className="alpha-research-equation">question → evidence → measurement → revision</div></div></section>
    <section id="method" className="alpha-home-method"><div><p className="alpha-eyebrow">THE WORKSPACE</p><h2>Less noise.<br/>More traceability.</h2></div><div className="alpha-home-cards"><article><span>01 / OBSERVATION</span><h3>A chart for investigation</h3><p>Historical replay, indicators, and drawings support your research. Chart candles remain a display, not evidence of an execution path.</p></article><article><span>02 / EXPERIMENT</span><h3>A method you can revisit</h3><p>Define your strategy, create a session, and review an order before confirming it. Return to the saved experiment without resetting its history.</p></article><article><span>03 / EVIDENCE</span><h3>Results with context</h3><p>Inspect committed outcomes and data limitations. Insufficient evidence remains unresolved rather than becoming an assumed fill.</p></article></div></section>
    <section id="principles" className="alpha-home-principles"><p className="alpha-eyebrow">RESEARCH PRINCIPLES</p><h2>Uncertainty is part of the result.</h2><p>Backtest Lab is an analytical tool, not a forecast or a promise of trading returns. The local Alpha uses imported historical data with explicit source limitations. Source attribution does not imply broker endorsement or public redistribution rights.</p><div><span>Data provenance</span><span>No look-ahead</span><span>Reproducible experiments</span><span>Explicit limitations</span></div></section>
    <footer className="alpha-home-footer"><span>Backtest Lab / Alpha</span><span>Research · mathematics · data science</span><a href={workspace}>Workspace ↗</a></footer>
  </main>;
}
