import { mkdir, writeFile, rename } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { unzipSync, strFromU8 } from 'fflate';
import { parseHistDataCSV } from '../src/market/history.js';

const month = process.argv[2] || '202609';
if (!/^20\d{2}(0[1-9]|1[0-2])$/.test(month)) throw new Error('Usage: npm run history:download -- YYYYMM');
const year = month.slice(0, 4), number = Number(month.slice(4));
const pageURL = `https://www.histdata.com/download-free-forex-historical-data/?/ascii/1-minute-bar-quotes/xauusd/${year}/${number}`;
const page = await fetch(pageURL, { signal: AbortSignal.timeout(30000) });
if (!page.ok) throw new Error(`Historical download page: HTTP ${page.status}`);
const html = await page.text();
const form = /<form id="file_down"[\s\S]*?<\/form>/.exec(html)?.[0];
if (!form) throw new Error('No historical file available for this month');
const parameters = new URLSearchParams();
for (const input of form.matchAll(/<input[^>]*name="([^"]+)"[^>]*value="([^"]*)"/g)) parameters.set(input[1], input[2]);
const response = await fetch('https://www.histdata.com/get.php', { method: 'POST', headers: { Referer: pageURL }, body: parameters, signal: AbortSignal.timeout(60000) });
if (!response.ok) throw new Error(`Historical file: HTTP ${response.status}`);
const bytes = new Uint8Array(await response.arrayBuffer());
if (bytes.length > 15000000 || bytes[0] !== 80 || bytes[1] !== 75) throw new Error('Response is not a supported ZIP file');
const files = unzipSync(bytes);
const name = Object.keys(files).find(name => name.endsWith('.csv') && name.includes('XAUUSD') && name.includes('M1'));
if (!name) throw new Error('XAU/USD M1 CSV missing in archive');
const candles = parseHistDataCSV(strFromU8(files[name]));
const payload = { symbol: 'XAUUSD', timeframe: '1m', source: 'HistData.com', priceType: 'bid', sourceURL: pageURL, sourceTimezone: 'EST fixed UTC-5', timezone: 'UTC', downloadedAt: new Date().toISOString(), requestedMonth: month, archiveSHA256: createHash('sha256').update(bytes).digest('hex'), count: candles.length, first: candles[0]?.time, last: candles.at(-1)?.time, candles };
await mkdir(new URL('../public/market/', import.meta.url), { recursive: true });
const target = new URL('../public/market/xauusd-history.json', import.meta.url), temporary = new URL('../public/market/xauusd-history.tmp', import.meta.url);
await writeFile(temporary, JSON.stringify(payload));
await rename(temporary, target);
console.log(JSON.stringify({ source: payload.source, count: payload.count, from: new Date(payload.first * 1000).toISOString(), to: new Date(payload.last * 1000).toISOString(), sha256: payload.archiveSHA256 }));
