import {useEffect,useRef,useState} from 'react';
export default function TradingLevels({chart,series,positions,orders,onAmend,onClose,onCancel,onError}){
  const [,refresh]=useState(0),[drag,setDrag]=useState(null),svg=useRef(null),moving=useRef(null);
  useEffect(()=>{let frame;const repaint=()=>{if(!frame)frame=requestAnimationFrame(()=>{frame=null;refresh(value=>value+1);});};chart?.timeScale().subscribeVisibleLogicalRangeChange(repaint);chart?.timeScale().subscribeSizeChange(repaint);window.addEventListener('pointermove',repaint);window.addEventListener('wheel',repaint);window.addEventListener('resize',repaint);return()=>{chart?.timeScale().unsubscribeVisibleLogicalRangeChange(repaint);chart?.timeScale().unsubscribeSizeChange(repaint);window.removeEventListener('pointermove',repaint);window.removeEventListener('wheel',repaint);window.removeEventListener('resize',repaint);if(frame)cancelAnimationFrame(frame);};},[chart]);
  if(!chart||!series)return null;
  const width=chart.timeScale().width(),height=chart.paneSize().height;
  const levels=[...positions.map(item=>({...item,pending:false})),...orders.map(item=>({...item,pending:true}))].flatMap(item=>['entry','sl','tp'].filter(key=>Number.isFinite(item[key])).map(key=>({item,key,price:drag?.id===item.id&&drag.key===key?drag.price:item[key]})));
  const down=(event,item,key)=>{if(key==='entry'&&!item.pending)return;event.preventDefault();event.stopPropagation();moving.current={id:item.id,key,price:item[key]};setDrag(moving.current);svg.current.setPointerCapture(event.pointerId);chart.applyOptions({handleScroll:{pressedMouseMove:false}});};
  const move=event=>{if(!moving.current)return;const price=series.coordinateToPrice(event.clientY-svg.current.getBoundingClientRect().top);if(price!=null){moving.current={...moving.current,price:Number(price.toFixed(3))};setDrag(moving.current);}};
  const up=event=>{if(!moving.current)return;const value=moving.current;moving.current=null;setDrag(null);if(svg.current.hasPointerCapture(event.pointerId))svg.current.releasePointerCapture(event.pointerId);chart.applyOptions({handleScroll:{pressedMouseMove:true}});try{onAmend(value.id,{[value.key]:value.price});}catch(error){onError?.(error.message);}};
  return <svg ref={svg} className="trading-levels" width="100%" height="100%" onPointerMove={move} onPointerUp={up} onPointerCancel={up} aria-label="Trading levels">{levels.map(({item,key,price})=>{const y=series.priceToCoordinate(price);if(y==null||y<8||y>height-8)return null;const color=key==='sl'?'#d74b5d':key==='tp'?'#14a783':item.pending?'#c29b49':'#3b77da';return <g key={item.id+key} onPointerDown={event=>down(event,item,key)} style={{pointerEvents:'all',cursor:key==='entry'&&!item.pending?'default':'ns-resize'}}>
    {(key!=='entry'||item.pending)&&<rect x="0" y={y-5} width={width} height="10" fill="transparent"/>}
    <rect x={Math.max(0,width-225)} y={y-10} width="150" height="20" rx="3" fill={color}/><text x={Math.max(4,width-218)} y={y+4} fill="white" fontSize="9">{key==='entry'?`${item.side} ${item.size.toFixed(4)}${item.pending?' '+item.type:''}`:`${key.toUpperCase()} ${price.toFixed(3)}`}</text>
    <rect x={width-75} y={y-10} width="20" height="20" rx="3" fill={color}/><text x={width-69} y={y+4} fill="white" fontSize="12" style={{cursor:'pointer'}} onPointerDown={event=>{event.stopPropagation();if(key==='entry'){if(item.pending)onCancel(item.id);else onClose(item.id);}else {try{onAmend(item.id,{[key]:null});}catch(error){onError?.(error.message);}}}}>×</text>
  </g>;})}</svg>;
}
