import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DrawingManager } from '../src/drawings/DrawingManager.js';
import { DrawingInteractionController, isEditable } from '../src/drawings/interaction/DrawingInteractionController.js';
import { hitSegment, HIT } from '../src/drawings/interaction/hitTesting.js';
import { continuousPointFromPointer, projectTimestamp } from '../src/drawings/timeCoordinates.js';

const bars = [{time:100}, {time:200}, {time:500}];
const scale = { timeToCoordinate: time => ({100:10,200:30,500:50})[time] ?? null };
const chart = {timeScale:()=>scale}, series = {coordinateToPrice:y=>100-y,priceToCoordinate:p=>100-p};
const manager = new DrawingManager(); manager.setTimePoints(bars);
const input = {id:'a',type:'trend-line',points:[{time:150,price:80},{time:350,price:60}]};
manager.add(input); manager.add({...input,id:'b'});
manager.select('a'); assert.equal(manager.selectedId,'a');
assert.equal(manager.primitives.get('a').selected,true);
manager.select('b'); assert.equal(manager.primitives.get('a').selected,false);
manager.select(null); assert.equal(manager.selectedId,null);
const controller = new DrawingInteractionController(manager,chart,series);
const a={x:20,y:20},b={x:40,y:40};
assert.equal(hitSegment({x:30,y:30},a,b),HIT.BODY);
assert.equal(hitSegment({x:30,y:33},a,b),HIT.BODY);
assert.equal(hitSegment({x:30,y:50},a,b),HIT.NONE);
assert.equal(hitSegment({x:19,y:19},a,b),HIT.NONE);
assert.equal(hitSegment(a,a,b,true),HIT.A);
assert.equal(hitSegment(b,a,b,true),HIT.B);
assert.equal(hitSegment(a,a,a,true),HIT.A);
assert.equal(hitSegment(a,a,a),HIT.BODY);
assert.equal(controller.hit(a).id,'b','Latest drawing wins ties');
manager.select('a'); assert.equal(controller.hit(a).type,HIT.A);
const original=manager.get('a').points;
controller.begin({id:'a',type:HIT.A},a); controller.move({x:25,y:25}); controller.finish();
assert.notDeepEqual(manager.get('a').points[0],original[0]); assert.deepEqual(manager.get('a').points[1],original[1]);
const afterA=manager.get('a').points;
controller.begin({id:'a',type:HIT.B},b); controller.move({x:45,y:35}); controller.finish();
assert.deepEqual(manager.get('a').points[0],afterA[0]); assert.notDeepEqual(manager.get('a').points[1],afterA[1]);
const beforeBody=manager.get('a').points;
controller.begin({id:'a',type:HIT.BODY},{x:30,y:30}); controller.move({x:35,y:25}); controller.finish();
const afterBody=manager.get('a').points;
assert.equal(afterBody[1].time-afterBody[0].time,beforeBody[1].time-beforeBody[0].time);
assert.equal(afterBody[1].price-afterBody[0].price,beforeBody[1].price-beforeBody[0].price);
assert.notDeepEqual(afterBody,beforeBody);
for (const cancel of [()=>controller.escape(),()=>controller.finish(true)]) {
  const before=manager.get('a').points;
  controller.begin({id:'a',type:HIT.A},a); controller.move({x:38,y:18}); cancel();
  assert.deepEqual(manager.get('a').points,before);
}
controller.escape(); assert.equal(manager.selectedId,null);
manager.select('a'); controller.deleteSelected(); assert.equal(manager.selectedId,null); assert.equal(manager.get('a'),undefined);
assert.ok(manager.get('b')); assert.throws(()=>manager.add({...input,type:'long-position'})); assert.throws(()=>manager.add({...input,type:'short-position'}));
assert.equal(isEditable({closest:()=>({})}),true); assert.equal(isEditable({closest:()=>null}),false);
const canonical=JSON.stringify(manager.get('b'));
manager.setTimePoints([{time:100},{time:500}]); manager.setTimePoints(bars);
assert.equal(JSON.stringify(manager.get('b')),canonical);
for (const x of [-10,20,35,70]) {
  const p=continuousPointFromPointer(chart,series,{x,y:20},bars);
  assert.equal(projectTimestamp(scale,bars,p.time),x);
}
assert.deepEqual(Object.keys(afterBody[0]).sort(),['price','time']);
const source=readFileSync(new URL('../src/drawings/interaction/DrawingInteractionController.js',import.meta.url),'utf8');
assert.ok(!source.includes('localStorage')&&!source.includes('setData('));
assert.deepEqual(readFileSync(new URL('../../docs/PHASE5_STORAGE_BEFORE.json',import.meta.url)),readFileSync(new URL('../../docs/PHASE5_STORAGE_AFTER.json',import.meta.url)));
// Exercise actual event arbitration and cancellation rather than only domain methods.
const events = new Map(), keys = new Map(); let captured = null;
const root = {addEventListener:(key,fn)=>events.set(key,fn),removeEventListener:key=>events.delete(key),setPointerCapture:id=>{captured=id;},hasPointerCapture:id=>captured===id,releasePointerCapture:()=>{captured=null;}};
const element = {parentElement:root,style:{},focus(){},contains:()=>true,getBoundingClientRect:()=>({left:0,top:0})};
const scroll={pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:false,mouseWheel:true};
let activeScroll=scroll;
chart.options=()=>({handleScroll:activeScroll}); chart.applyOptions=options=>{activeScroll=options.handleScroll;}; chart.paneSize=()=>({height:100}); scale.width=()=>100;
globalThis.window={addEventListener:(key,fn)=>keys.set(key,fn),removeEventListener:key=>keys.delete(key)};
const cleanup=controller.bind(element);
const event=(x,y,target={closest:()=>null})=>({button:0,pointerId:1,clientX:x,clientY:y,target,preventDefault(){},stopPropagation(){},stopImmediatePropagation(){}});
const initial=manager.get('b').points;
events.get('pointerdown')(event(30,30)); assert.equal(activeScroll.pressedMouseMove,false);
events.get('pointermove')(event(35,35)); events.get('pointercancel')();
assert.deepEqual(manager.get('b').points,initial); assert.deepEqual(activeScroll,scroll); assert.equal(element.style.cursor,'');
events.get('pointerdown')(event(30,30)); events.get('pointermove')(event(35,35));
keys.get('keydown')({...event(0,0),key:'Escape'}); assert.deepEqual(manager.get('b').points,initial);
manager.select('b'); keys.get('keydown')({...event(0,0,{closest:()=>({})}),key:'Delete'}); assert.ok(manager.get('b'));
events.get('pointerdown')(event(30,30,{closest:()=>({})})); assert.equal(controller.drag,null,'Trading target must not start drawing drag');
keys.get('keydown')({...event(0,0),key:'Delete'}); assert.equal(manager.get('b'),undefined); assert.equal(manager.selectedId,null);
cleanup(); delete globalThis.window;
console.log('PASS Phase 6 selection, finite segment/handle priority, continuous inverse projection, A/B/body drag, cancellation, delete, canonical coordinates and isolation.');
