import assert from 'node:assert/strict';
import { validateDataset, importDataset, utcTimestamp, endOfSourceDay, canonicalString } from '../src/news/eventValidation.js';
import { EventIndex, DEFAULT_FILTERS } from '../src/news/eventIndex.js';
import { DEFAULT_WINDOW, validateWindow, classifyWindow, contextAt } from '../src/news/researchContext.js';
import { markerGroups, NewsMarkerAdapter } from '../src/news/NewsMarkerAdapter.js';
import { validatePreferences } from '../src/news/eventRepository.js';
import { NewsNavigationController } from '../src/news/NewsNavigationController.js';
import { START, pilot, fact, iso } from './phase14-5-fixtures.mjs';
import './phase14-5-navigation.test.mjs';
const raw = pilot(), dataset = validateDataset(raw), index = new EventIndex(dataset);
const all = { currency: 'All', impact: 'All', category: 'All' }, release = START + 1800;
assert.ok(Object.isFrozen(dataset.occurrences[0].facts.actual[0]));
const snapshot = (data, time) => {
  const query = new EventIndex(validateDataset(data));
  return { events: query.range(START - 86400, START + 86400, time, DEFAULT_FILTERS), next: query.navigate(time, 1, DEFAULT_FILTERS), previous: query.navigate(time, -1, DEFAULT_FILTERS), context: contextAt(query, time, time, DEFAULT_FILTERS, DEFAULT_WINDOW) };
};
for (const field of ['actual', 'forecast', 'previous', 'schedule', 'impact']) {
  const original = pilot(); original.occurrences[0].facts[field].push(fact(field === 'schedule' ? iso(release + 5000) : field === 'impact' ? 'Low' : 99, START + 7200, { version: 'future', ...(['actual', 'forecast', 'previous'].includes(field) ? { unit: '%', rawText: '99%' } : {}) }));
  const changed = structuredClone(original);
  changed.occurrences[0].facts[field].at(-1).value = field === 'schedule' ? iso(release + 10000) : field === 'impact' ? 'Medium' : -999;
  for (const time of [START, release - .001, release, START + 7199.999]) assert.deepEqual(snapshot(changed, time), snapshot(original, time), `Future ${field} cannot affect output at ${time}.`);
  const truncated = structuredClone(original);
  for (const item of truncated.occurrences) for (const key of Object.keys(item.facts)) item.facts[key] = item.facts[key].filter(value => value.availableAtUtc !== null && Date.parse(value.availableAtUtc) / 1000 <= START);
  assert.deepEqual(snapshot(truncated, START), snapshot(original, START), 'Physical future fact truncation is invariant.');
}
let before = index.range(START, START + 86400, release - .001, all);
assert.equal(before[0].fields.actual, undefined); assert.equal(before[0].fields.forecast.value, 2);
assert.equal(index.range(START, START + 86400, release, all)[0].fields.actual.value, 3);
assert.equal(index.range(START, START + 86400, START, all)[0].fields.actual, undefined, 'Rewind restores original view.');
assert.equal(index.range(START, START + 86400, START, DEFAULT_FILTERS).length, 5);
assert.equal(index.range(START, START + 86400, START, { ...all, currency: 'EUR' }).length, 1);
assert.equal(index.range(START, START + 86400, START, { ...all, category: 'GDP' }).length, 1);
assert.equal(index.navigate(START, 1, DEFAULT_FILTERS).time, release);
assert.equal(index.navigate(release, -1, DEFAULT_FILTERS), null);
assert.equal(index.navigate(release, 1, DEFAULT_FILTERS).time, release + 1800);
const simultaneous = pilot(); simultaneous.occurrences[1].facts.schedule[0].value = iso(release);
assert.equal(new EventIndex(validateDataset(simultaneous)).navigate(START, 1, DEFAULT_FILTERS).events.length, 2);
const hidden = pilot(); hidden.occurrences[0].facts.impact[0].availableAtUtc = null;
assert.equal(new EventIndex(validateDataset(hidden)).range(START, START + 86400, START, DEFAULT_FILTERS).length, 4);
const cancelled = pilot(); cancelled.occurrences[0].facts.status.push(fact('cancelled', START + 60, { version: 'cancel' }));
assert.equal(new EventIndex(validateDataset(cancelled)).range(START, START + 86400, START + 61, all).length, 5);
const quality = new EventIndex(validateDataset({ ...pilot(), coverage: [{ ...pilot().coverage[0], status: 'partial' }] }));
assert.equal(index.coverageAt(START, all), 'complete'); assert.equal(index.coverageAt(START - 86400 * 10, all), 'unknown'); assert.equal(quality.coverageAt(START, all), 'partial');
for (const [offset, expected] of [[-3600, 'Pre'], [-1, 'Pre'], [0, 'During'], [59.999, 'During'], [60, 'Post'], [3599.999, 'Post'], [3600, null], [-3600.001, null]]) assert.equal(classifyWindow(offset, DEFAULT_WINDOW), expected);
assert.equal(classifyWindow(0, validateWindow({ ...DEFAULT_WINDOW, C: 0 })), 'Post');
assert.throws(() => validateWindow({ ...DEFAULT_WINDOW, B: 4000 }));
assert.throws(() => validatePreferences({ filters: { ...all, impact: '<script>' } }));
const context = contextAt(index, START + 3600, START + 3600, DEFAULT_FILTERS, DEFAULT_WINDOW);
assert.ok(context.matches.length > 1); assert.equal(context.nearest.delta, 0); assert.equal(context.nearest.window, 'During');
assert.equal(contextAt(index, null, START, all, DEFAULT_WINDOW).status, 'unknown');
assert.equal(utcTimestamp('2024-03-10T03:30:00-04:00', 'test', 'America/New_York'), Date.parse('2024-03-10T07:30:00Z') / 1000);
assert.throws(() => utcTimestamp('2024-03-10T02:30:00-05:00', 'test', 'America/New_York'));
assert.notEqual(utcTimestamp('2024-11-03T01:30:00-04:00', 'test', 'America/New_York'), utcTimestamp('2024-11-03T01:30:00-05:00', 'test', 'America/New_York'));
assert.equal(endOfSourceDay('2024-03-10', 'America/New_York'), Date.parse('2024-03-11T04:00:00Z') / 1000);
assert.throws(() => utcTimestamp('2024-02-30T12:00:00Z')); assert.throws(() => utcTimestamp('2024-06-03T12:00:00')); assert.throws(() => utcTimestamp('2024-06-03T12:00:00Z', 'test', 'Wrong/Zone'));
const coarse = pilot(); coarse.occurrences[0].facts.schedule = [fact('2024-06-03', START - 86400, { precision: 'day', sourceTimestamp: '2024-06-03' })];
const coarseIndex = new EventIndex(validateDataset(coarse)); assert.equal(coarseIndex.dateOnly(START, all).length, 1); assert.notEqual(coarseIndex.navigate(START, 1, all).events[0].occurrenceId, coarse.occurrences[0].occurrenceId);
const dayAvailability = pilot(); dayAvailability.occurrences[0].facts.impact[0].availableAtUtc = '2024-06-03'; dayAvailability.occurrences[0].facts.impact[0].availabilityPrecision = 'day';
assert.equal(new EventIndex(validateDataset(dayAvailability)).range(START, START + 86400, START, DEFAULT_FILTERS).length, 4);
for (const mutate of [d => { d.schemaVersion = 2; }, d => { d.occurrences.push(d.occurrences[0]); }, d => { d.definitions.push(d.definitions[0]); }, d => { d.occurrences[0].facts.actual[0].value = NaN; }, d => { d.occurrences[0].facts.impact[0].evidence = ''; }, d => { d.occurrences[0].facts.name.push(d.occurrences[0].facts.name[0]); }]) { const data = pilot(); mutate(data); assert.throws(() => validateDataset(data)); }
assert.throws(() => validateDataset({ ...pilot(), coverage: [{ ...pilot().coverage[0], to: '2024-06-01T00:00:00Z' }] }));
await assert.rejects(importDataset('not JSON')); await assert.rejects(importDataset('[]'));
const normal = await importDataset(JSON.stringify(raw)), reordered = structuredClone(raw); reordered.occurrences.reverse(); reordered.definitions.reverse();
const second = await importDataset(JSON.stringify(reordered)); assert.equal(normal.hash, second.hash); assert.notEqual(normal.sourceHash, second.sourceHash); assert.equal(canonicalString(normal.dataset), canonicalString(second.dataset));
const revealed = [{ time: release - 60 }, { time: release }], events = index.range(START, release + 1, release, all);
assert.equal(markerGroups(events, revealed, '1m', time => time === release, release).length, 1);
assert.equal(markerGroups(events, revealed, '1m', () => false, release).length, 0, 'No gap floor mapping.');
assert.equal(markerGroups(events, revealed, '1m', () => true, release - 1).length, 0, 'No future markers.');
const primitive = new NewsMarkerAdapter(); let requests = 0; primitive.attached({ chart: { paneSize: () => ({ height: 200 }), timeScale: () => ({ timeToCoordinate: () => 50 }) }, requestUpdate: () => requests++ }); primitive.replace([{ time: release, events }]); assert.ok(primitive.hit(50, 182)); assert.equal(requests, 1); primitive.detached(); assert.equal(primitive.hit(50, 182), undefined);
const nav = new NewsNavigationController(); nav.begin(release, { time: START }); assert.equal(nav.commit({ time: START, revision: 1, settledTime: START, active: true, atEnd: true }), 'waiting-for-history'); nav.cancel(); assert.equal(nav.target, null);
console.log('PASS canonical import, timezone/DST, versioning, strict mutation/truncation invariance, filters, windows, coverage, marker gaps/lifecycle and navigation.');
