import assert from 'node:assert/strict';
import {SAMPLE_METHODS,DEMO_PROFILE,createMethod,constrainPlan,preview,makeRequest,validateRequest,confirmRequest,manage,amendExits} from '../src/tradingUx/prototypeModel.js';
const [free,on,off]=SAMPLE_METHODS,quote={price:2332,revision:1};
const plan={workflow:'PLANNED',side:'Buy',type:'Limit',entry:2330,sl:2328,tp:2334,riskMode:'PERCENT',risk:1,checklist:{}};
assert.throws(()=>createMethod({name:'x',rr:2,risk:1,conditions:[]}));
assert.throws(()=>createMethod({name:'x',rr:0,risk:1,conditions:['x']}));
assert.equal(createMethod({name:'Valid',rr:2,risk:1,conditions:['x'],enforcement:false}).conditions.length,1);
let request=makeRequest(free,plan,quote,1,'one');
assert.deepEqual(validateRequest(free,request,quote,1),[]);
assert.equal(preview(free,plan).size,5);
assert(preview(free,{...plan,sl:2327.999}).loss<=1000+1e-8,'Never round risk up');
assert(validateRequest(free,{...request,sl:2335},quote,1).length);
assert(validateRequest(free,{...request,entry:2330.0005},quote,1).some(r=>r.startsWith('PRECISION')));
assert(validateRequest(free,{...request,feedId:'other'},quote,1).some(r=>r.startsWith('IDENTITY')));
assert(validateRequest(free,request,quote,2).some(r=>r.startsWith('STALE')));
assert(validateRequest(free,request,{...quote,revision:2},1).some(r=>r.startsWith('STALE')));
assert(validateRequest(free,request,{price:NaN,revision:1},1).some(r=>r.startsWith('QUOTE')));
assert(validateRequest(free,{...request,size:1001},quote,1).some(r=>r.startsWith('SIZE')));
request=makeRequest(on,plan,quote,1,'on');
assert.equal(request.checklist['Setup identified'],'NOT_ASSESSED');
assert.equal(validateRequest(on,request,quote,1).filter(r=>r.startsWith('CHECKLIST')).length,2);
request=makeRequest(on,{...plan,checklist:Object.fromEntries(on.conditions.map(c=>[c,'PASS']))},quote,1,'on');
assert.deepEqual(validateRequest(on,request,quote,1),[]);
for(const [field,value] of [['workflow','QUICK'],['type','Market'],['risk',2],['tp',2335],['size',4]]) assert(validateRequest(on,{...request,[field]:value},quote,1).some(r=>r.startsWith('PROTOCOL')),field+' bypass refused');
const offRequest=makeRequest(off,{...plan,checklist:{'Setup identified':'FAIL'}},quote,1,'off');
assert.deepEqual(validateRequest(off,offRequest,quote,1),[]);
assert.equal(offRequest.checklist['Stop defined'],'NOT_ASSESSED');assert.equal(offRequest.checklist['Setup identified'],'FAIL');
assert(validateRequest(off,{...offRequest,type:'Market'},quote,1).some(r=>r.startsWith('PROTOCOL')));
const moved=constrainPlan(on,{...plan,sl:2327,tp:9999,risk:50});assert.equal(moved.tp,2336);assert.equal(moved.risk,1);assert.equal(preview(on,moved).size,Math.floor((1000/300)/DEMO_PROFILE.step)*DEMO_PROFILE.step);
const short=makeRequest(on,{...plan,side:'Sell',entry:2334,sl:2336,tp:2330,checklist:request.checklist},quote,1,'short');assert.deepEqual(validateRequest(on,short,quote,1),[]);
const quick=makeRequest(free,{...plan,workflow:'QUICK',type:'Market',sl:null,tp:null,size:1},quote,1,'quick');assert.deepEqual(validateRequest(free,quick,quote,1),[]);
let out=confirmRequest({},free,quick,quote,1);assert.equal(out.result.state,'active_position');const before=JSON.stringify(out.registry);
let again=confirmRequest(out.registry,free,quick,quote,1);assert.equal(again.duplicate,true);assert.equal(JSON.stringify(again.registry),before);
assert(confirmRequest(out.registry,free,{...quick,size:2},quote,1).reasons[0].startsWith('IDEMPOTENCY_CONFLICT'));
assert(confirmRequest({},free,quick,quote,2).reasons.length);
out=confirmRequest({},on,request,quote,1);assert.equal(out.result.state,'pending');
assert.equal(manage(on,out.result,'cancel').item.state,'cancelled');
const active=manage(on,out.result,'trigger').item;for(const action of ['partial','close','amend'])assert(manage(on,active,action).reason.startsWith('PROTOCOL'));
assert.equal(manage(on,active,'plannedExit').item.state,'closed');
assert.equal(manage(free,active,'partial').item.remaining,.5);assert.equal(manage(free,active,'close').item.state,'closed');assert(manage(free,active,'amend').amend);
const amended=amendExits(free,active,2327,2335);assert.equal(amended.item.request,active.request);assert.deepEqual(amended.item.currentExits,{sl:2327,tp:2335});assert(amendExits(on,active,2327,2335).reason);assert(amendExits(free,active,2335,2336).reason);
console.log('PASS Phase18.8 Method validation, units/risk rounding, Long/Short, Quick/Planned, checklist ON/OFF/unknown evidence, bypass/stale refusal, idempotent confirmation and lifecycle restrictions.');
