import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {api,command,sessionPath,loadResearchContext,noticeText} from '../src/tickAlpha/client.js';
import {syncTickAnnotations,ratioLabel} from '../src/tickAlpha/annotations.js';
import {displayBars,replayTarget,seekTarget} from '../src/tickAlpha/display.js';

const calls=[];
globalThis.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({schemaVersion:1,reviewHash:'pinned'})};};
const exact='0.123456789012345678';
await api('/reviews',{draft:{quantity:exact},expectedRevision:7});
assert.equal(JSON.parse(calls[0].options.body).draft.quantity,exact);
assert.equal(calls[0].options.credentials,'omit');
assert.equal(calls[0].options.cache,'no-store');
assert.equal(calls[0].options.headers['X-BTL-Local'],'1');
await api('/catalog');
assert.equal(calls[1].options.method,'GET');assert.ok(!Object.hasOwn(calls[1].options,'body'));
assert.equal(sessionPath('session:α'),'/sessions/session%3A%CE%B1');
const raw=command({metadata:{id:'session:one'},state:{revision:7}},'ADVANCE',{targetNs:'1577838600000000000'});
assert.equal(raw.expectedRevision,7);assert.equal(raw.payload.targetNs,'1577838600000000000');
assert.notEqual(raw.commandId,command({metadata:{id:'session:one'},state:{revision:7}},'ADVANCE',raw.payload).commandId);
globalThis.fetch=async()=>({ok:false,json:async()=>({detail:'REFUSED_STALE_REVISION'})});
await assert.rejects(()=>api('/reviews',{}),/REFUSED_STALE_REVISION/);
globalThis.fetch=async()=>({ok:true,json:async()=>({schemaVersion:2})});
await assert.rejects(()=>api('/catalog'),/Unsupported local response/);
const ui=readFileSync(new URL('../src/tickAlpha/TickAlpha.jsx',import.meta.url),'utf8');
for(const prohibited of ['useTrading','prototypeModel','localStorage','simulate trigger','manage('])assert.ok(!ui.includes(prohibited),'Alpha must not adopt a second financial truth: '+prohibited);
assert.ok(ui.includes('review.reviewHash')&&ui.includes("+'/confirm'"));
assert.ok(ui.includes('flight.current')&&ui.includes('loadWorkspace(view.metadata.id)'));
const main=readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
assert.ok(main.includes("get('tick-alpha')==='local'"));assert.ok(main.includes('localOrigin?<TickAlphaEntry/>'));
console.log('PASS tick-alpha transport exact strings, explicit revision/command identity, local-only opt-in and durable-review UI boundary.');

const view={state:{throughNs:'1577838600000000000'},chart:{timeframe:'1m',priceBasis:'EXACT_REVEALED_MID_DISPLAY_ONLY',volumeAvailable:false,candles:[
  {time:1577838540,open:'2000.015',high:'2001.015',low:'1999.015',close:'2000.515',event_count:4,incomplete:false,partialWindow:false},
]}};
const bars=displayBars(view);
assert.equal(bars[0].open,2000.015);assert.ok(!Object.hasOwn(bars[0],'volume'));
assert.deepEqual(Object.keys(bars[0]),['time','open','high','low','close']);
assert.equal(view.chart.candles[0].open,'2000.015');
assert.equal(replayTarget(view,4),'1577838660000000000');
assert.equal(seekTarget('2020-01-01T00:30'),'1577838600000000000');
assert.throws(()=>replayTarget(view,1000));assert.throws(()=>seekTarget('2020-01-01T00:30Z'));
const future=structuredClone(view);future.chart.candles[0].time=1577838660;
assert.throws(()=>displayBars(future),/Unrevealed/);
const bad=structuredClone(view);bad.chart.candles[0].open=2000.015;
assert.throws(()=>displayBars(bad),/display price/);
const volume=structuredClone(view);volume.chart.volumeAvailable=true;
assert.throws(()=>displayBars(volume),/Invalid revealed/);
console.log('PASS revealed-only display projection, no fabricated volume, immutable exact wire prices and exact tick/UTC targets.');

const chartLines=[],removed=[],chartMarkers=[];
const series={createPriceLine:line=>{chartLines.push(line);return line;},removePriceLine:line=>removed.push(line)};
const projection={status:'COMPLETE',annotations:[{eventId:'fill:exact',timeNs:'1577838540000000000',price:'2000.02',side:'LONG',kind:'ENTRY_FILL',chronologyLimited:false}],orders:[{status:'ACTIVE',side:'LONG',entryPrice:'2000.02',entry:'2000',sl:'1998',tp:'2004'}]};
const priceLines=syncTickAnnotations({series,markerPlugin:{setMarkers:markers=>chartMarkers.push(...markers)},candles:bars,evidence:projection});
assert.equal(chartMarkers[0].id,'fill:exact');assert.equal(chartMarkers[0].time,1577838540);
assert.equal(chartMarkers[0].text,'Entry @ 2000.02');assert.equal(priceLines[0].price,2000.02);
assert.notEqual(priceLines[0].price,bars[0].open,'Fill annotation retains actual Ask, not candle mid');
assert.equal(projection.annotations[0].price,'2000.02');
syncTickAnnotations({series,markerPlugin:{setMarkers:markers=>assert.deepEqual(markers,[])},priceLines,candles:bars,evidence:{status:'UNAVAILABLE'}});
assert.equal(removed.length,3);
assert.equal(ratioLabel({numerator:'3',denominator:'7'},{percent:true}),'42.86%');
assert.equal(ratioLabel({numerator:'-45',denominator:'7'}),'-6.43');
assert.equal(ratioLabel(null),'Unavailable');assert.throws(()=>ratioLabel({numerator:'1',denominator:'0'}));
console.log('PASS actual fill identity/price chart annotation, unavailable-history clearing and exact rational display rounding.');

// An obsolete bootstrap must not spend a workspace worker slot or load a Session.
const bootstrapCalls=[];
globalThis.fetch=async(url,options)=>{bootstrapCalls.push({url,options});return {ok:true,json:async()=>({schemaVersion:1,methods:[],sessions:[]})};};
assert.equal(await loadResearchContext('session:obsolete',{active:()=>false}),null);
assert.equal(bootstrapCalls.length,1);
assert.equal(bootstrapCalls[0].options.method,'GET');
bootstrapCalls.length=0;
const reopened=await loadResearchContext('session:saved',{timeframe:'5m'});
assert.equal(bootstrapCalls.length,2);assert.ok(bootstrapCalls[1].url.endsWith('/sessions/session%3Asaved/view'));
assert.deepEqual(JSON.parse(bootstrapCalls[1].options.body),{timeframe:'5m'});
assert.ok(reopened.catalog&&reopened.view);
assert.ok(noticeText('REFUSED_REWIND_REQUIRES_FORK').includes('Create a separate Session'));
assert.ok(noticeText('REFUSED_REWIND_REQUIRES_FORK').includes('REFUSED_REWIND_REQUIRES_FORK'));
assert.equal(noticeText('UNKNOWN_BOUNDARY'),'UNKNOWN_BOUNDARY');
console.log('PASS obsolete-bootstrap cancellation, saved-session reconnect and honest refusal guidance without command mutation.');
