import {useState} from 'react';
import {money} from './format';
import {utcTime} from './backtestAnalysis.js';
export default function Journal({account,onClose,onNotes}){
  const [tab,setTab]=useState('Trades'),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[month,setMonth]=useState(()=>new Date().toISOString().slice(0,7));
  const trades=account.trades.filter(item=>(`XAUUSD ${item.side} ${item.tags} ${item.strategy} ${item.reason}`).toLowerCase().includes(search.toLowerCase())).slice().reverse();
  const detail=account.trades.find(item=>item.id===selected),days=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();
  return <aside className="fx-journal" aria-label="Journal"><header><strong>Journal · exit records</strong><button aria-label="Close Journal" onClick={onClose}>×</button></header><div className="journal-tabs">{['Trades','Calendar'].map(value=><button key={value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{value}</button>)}</div>
    {tab==='Trades'?<><input className="journal-search-input" placeholder="Search trades" value={search} onChange={event=>setSearch(event.target.value)}/><div className="journal-trades">{trades.length?trades.map(item=><button key={item.id} className={item.id===selected?'selected':''} onClick={()=>setSelected(item.id)}><span>XAUUSD, {item.side?.toLowerCase()??'unknown'}</span><strong className={item.pnl>=0?'positive':'negative'}>{item.pnl>=0?'+':''}{money(item.pnl)}</strong><small>{utcTime(item.exitTime)?.replace('T',' ').slice(0,19)??'Exit time unavailable'}</small></button>):<p>No trades here yet</p>}</div>{detail&&<section className="journal-detail"><strong>{detail.strategy||'Session default'}</strong><span>{detail.reason} · {detail.size.toFixed(4)} lots</span><label>Notes<textarea aria-label="Trade notes" value={detail.notes||''} onChange={event=>onNotes(detail.id,event.target.value)}/></label><span>{detail.tags}</span></section>}</>:<><input type="month" aria-label="Journal month" value={month} onChange={event=>setMonth(event.target.value)}/><div className="journal-calendar">{Array.from({length:days},(_,i)=>{const prefix=`${month}-${String(i+1).padStart(2,'0')}`;const rows=account.trades.filter(item=>utcTime(item.exitTime)?.startsWith(prefix));const profit=rows.reduce((sum,item)=>sum+item.pnl,0);return <div key={i}><span>{i+1}</span>{rows.length>0&&<><strong className={profit>=0?'positive':'negative'}>{money(profit)}</strong><small>{rows.length} exits</small></>}</div>;})}</div></>}
  </aside>;
}
