import {useState} from 'react';
import {CONTRACT_SIZE,validateOrder} from './simulator';
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);
export default function OrderTicket({side,price,balance,initialBalance,initialSize=1,seed,onPlace,onClose,onPickPrice}){
  const [form,setForm]=useState(()=>({side:seed?.side??side,type:seed?.type??'Market',size:seed?.size??initialSize,entry:seed?.entry??price,sl:seed?.sl??Number((price*(side==='Buy'?.99:1.01)).toFixed(3)),tp:seed?.tp??Number((price*(side==='Buy'?1.02:.98)).toFixed(3)),useSL:seed?.sl!=null,useTP:seed?.tp!=null,basis:'Current balance',risk:null,unit:'Lots',tags:'',strategy:'Session default',journal:false,partials:[]}));
  const [error,setError]=useState(''),[presetOpen,setPresetOpen]=useState(false);
  const entry=form.type==='Market'?price:Number(form.entry),riskBase=form.basis==='Initial balance'?initialBalance:balance;
  const distance=Math.abs(entry-Number(form.sl));
  const effectiveSize=form.risk!=null&&form.useSL&&distance>0?Math.floor(riskBase*Number(form.risk)/100/(distance*CONTRACT_SIZE)*10000)/10000:Number(form.size);
  const loss=form.useSL?Math.abs(entry-Number(form.sl))*effectiveSize*CONTRACT_SIZE:0,profit=form.useTP?Math.abs(Number(form.tp)-entry)*effectiveSize*CONTRACT_SIZE:0;
  const change=(key,value)=>setForm(current=>{const next={...current,[key]:value};if(['sl','entry','basis','risk','useSL','type'].includes(key)&&next.risk!=null&&next.useSL){const entry=next.type==='Market'?price:Number(next.entry);const distance=Math.abs(entry-Number(next.sl));if(distance>0)next.size=Number(((next.basis==='Initial balance'?initialBalance:balance)*Number(next.risk)/100/(distance*CONTRACT_SIZE)).toFixed(4));}return next;});
  const switchSide=value=>setForm(current=>({...current,side:value,sl:Number((entry*(value==='Buy'?.99:1.01)).toFixed(3)),tp:Number((entry*(value==='Buy'?1.02:.98)).toFixed(3)),risk:null}));
  const order={side:form.side,type:form.type,size:effectiveSize,entry,sl:form.useSL?Number(form.sl):null,tp:form.useTP?Number(form.tp):null,tags:form.tags,strategy:form.strategy,partials:form.useTP?form.partials.map(item=>({...item,price:Number(item.price),percent:Number(item.percent)})):[]};
  const submit=event=>{event.preventDefault();const message=validateOrder(order,price);if(message){setError(message);return;}try{onPlace(order,form.journal);onClose();}catch(error){setError(error.message);}};
  const input=(label,key,disabled=false)=><label className="ticket-field">{label}<div><input aria-label={label} type="number" step="any" min="0.0001" disabled={disabled} value={disabled?(price?.toFixed(3)??''):form[key]} onChange={event=>{change(key,event.target.value);setError('');}} /><button type="button" disabled={disabled} title={`Pick ${label.toLowerCase()} on chart`} aria-label={`Pick ${label.toLowerCase()} on chart`} onClick={()=>onPickPrice(key,value=>change(key,value))}>⌖</button></div></label>;
  return <aside className="fx-order-ticket order-popup" role="dialog" aria-labelledby="order-popup-title">
    <header><div className="order-popup-heading"><strong id="order-popup-title">Place Order</strong><span>XAUUSD</span></div><div><button type="button" onClick={()=>setPresetOpen(value=>!value)}>☷ Presets</button><button type="button" aria-label="Close order panel" onClick={onClose}>×</button></div></header>
    <form onSubmit={submit}>
      <div className="ticket-scroll">
        {presetOpen&&<div className="ticket-presets">{[1,2,3].map(ratio=><button type="button" key={ratio} onClick={()=>{change('useSL',true);change('useTP',true);change('tp',entry+(entry-Number(form.sl))*ratio);setPresetOpen(false);}}>Risk / Reward 1:{ratio}</button>)}</div>}
        <div className="ticket-segment side">{['Sell','Buy'].map(value=><button type="button" key={value} className={form.side===value?'active '+value.toLowerCase():''} onClick={()=>switchSide(value)}>{value}</button>)}</div>
        <div className="ticket-segment balance-basis">{['Initial balance','Current balance'].map(value=><label key={value}><input type="radio" name="balance" checked={form.basis===value} onChange={()=>change('basis',value)} />{value}</label>)}</div>
        <label className="ticket-caption">Set risk percentage</label><div className="risk-presets">{[.5,1,2,3].map(value=><button type="button" disabled={!form.useSL} className={form.risk===value?'active':''} key={value} onClick={()=>change('risk',value)}>{value}%</button>)}<label className={!form.useSL?'disabled':''}><input aria-label="Custom risk percentage" type="number" step="any" min="0.01" max="100" disabled={!form.useSL} placeholder="Custom" value={[.5,1,2,3].includes(form.risk)||form.risk==null?'':form.risk} onChange={event=>change('risk',Number(event.target.value))} /></label></div>
        <div className="ticket-summary"><div>Est. loss<strong className="negative">-{money(loss)}</strong></div><div>Est. profit<strong className="positive">+{money(profit)}</strong></div><div>R:R ratio<strong>{loss&&profit?`1:${(profit/loss).toFixed(2)}`:'—'}</strong></div></div>
        <label className="ticket-caption">Type</label><div className="ticket-segment">{['Market','Limit','Stop'].map(value=><button type="button" key={value} className={form.type===value?'active':''} onClick={()=>change('type',value)}>{value}</button>)}</div>
        <div className="ticket-fields"><label className="ticket-field"><select aria-label="Size unit" value={form.unit} onChange={event=>change('unit',event.target.value)}><option>Lots</option><option>Units</option></select><input aria-label="Order size" type="number" step="any" min="0.0001" value={form.unit==='Units'?effectiveSize*CONTRACT_SIZE:effectiveSize} onChange={event=>{change('size',form.unit==='Units'?Number(event.target.value)/CONTRACT_SIZE:event.target.value);change('risk',null);}} /></label>{input('Entry price','entry',form.type==='Market')}</div>
        <div className="ticket-caption exits-caption">Exits{loss&&profit?<span> · Risk / Reward {(profit/loss).toFixed(2)}</span>:null}</div>
        <label className="ticket-switch"><input type="checkbox" role="switch" aria-label="Stop loss" checked={form.useSL} onChange={event=>change('useSL',event.target.checked)} /><span />Stop loss</label>{form.useSL&&input('Stop loss price','sl')}
        <label className="ticket-switch"><input type="checkbox" role="switch" aria-label="Take profit" checked={form.useTP} onChange={event=>change('useTP',event.target.checked)} /><span />Take profit</label>{form.useTP&&<>{input('Take profit price','tp')}{form.partials.map((item,index)=><div className="ticket-partial" key={item.id}><label>Target {index+1}<input aria-label={`Partial target ${index+1}`} type="number" step="any" value={item.price} onChange={event=>change('partials',form.partials.map(row=>row.id===item.id?{...row,price:event.target.value}:row))}/></label><label>Close %<input aria-label={`Partial close percentage ${index+1}`} type="number" min="1" max="99" value={item.percent} onChange={event=>change('partials',form.partials.map(row=>row.id===item.id?{...row,percent:event.target.value}:row))}/></label><button type="button" aria-label={`Remove partial ${index+1}`} onClick={()=>change('partials',form.partials.filter(row=>row.id!==item.id))}>×</button></div>)}<button type="button" className="add-partial" onClick={()=>change('partials',[...form.partials,{id:crypto.randomUUID(),price:Number(((entry+Number(form.tp))/2).toFixed(3)),percent:25}])}>+ Add partial</button></>}
        <label className="ticket-field">Tags<input placeholder="Search tags..." value={form.tags} onChange={event=>change('tags',event.target.value)} /></label>
        <label className="ticket-field">Strategy<input list="strategies" value={form.strategy} onChange={event=>change('strategy',event.target.value)} /><datalist id="strategies"><option>Session default</option><option>Breakout</option><option>Trend following</option><option>Reversal</option></datalist></label>
        {error&&<p className="ticket-error" role="alert">{error}</p>}<small className="ticket-account">Risk basis {money(riskBase)}</small>
      </div>
      <footer><label><input type="checkbox" checked={form.journal} onChange={event=>change('journal',event.target.checked)} />Open journal after placing</label><div className="order-popup-actions"><button type="button" className="discard-order" onClick={onClose}>Discard</button><button type="submit" className="place-order" disabled={!Number.isFinite(price)}>Place order</button></div></footer>
    </form>
  </aside>;
}
